### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/VisualDL#80]
- scalar
  - [x] 默认关闭 outlier
  - [x] 数据刷新失败，则停止刷新，保持原状，避免空白控件的出现 -[1级]
  - [x] 多个线条颜色(等美研小伙伴给配色)
  - [ ] legend 要用富文本
- 页面布局
  - [x] 根据设计修改
  - [x] margin 修改
  - [x] 浏览器tab里边的VisualDL加一个空格，变成Visual DL
  - [x] 拉到最上边的时候，banner那一栏看不到了
- graph
   - [x] 下午ready
   - [x] 配色
   - [ ] 图片映射到画布大小-[1 级]
   - [ ] 缩略图位置固定 - [2级]
   - [x] 用鼠标拖动 graph，松开鼠标图片会弹回去 
- demo
   - [ ] pytorch
   - [x] mxnet
   - [x] [paddle](https://github.com/PaddlePaddle/VisualDL/blob/develop/demo/paddle/cifar10_image_classification_vgg.py)
- histogram
  - [x] histogram 尖头部分超出容器，自适应一下
  - [x] histogram 底部的 放大缩小按钮点了无效，并且报 offsetWidth 的错 - [0级] 
  - [ ] 加最值的线
  - [x] mouseout， circle dot 没清掉
  - [x] 鼠标hover，每个 polygon 对应的 circle 没生效
  - [x] 搜索筛选
  - [x] 优化下每个多边形的间距
  - [x] 优化下渐变色
  - [x] 修改overlay 的问题 -[0级]
- image
  - [x] 能不能加个判断，每次只 update 用户打开的图片
- frontend 代码优化
  - [ ] 优化下代码的结构
  - [x] 添加代码注释
- backend 代码整理
  - [x] sdk 添加注释 [issue](https://github.com/PaddlePaddle/VisualDL/issues/93) [pr](https://github.com/PaddlePaddle/VisualDL/pull/96)
  - [x] refactor command line args https://github.com/PaddlePaddle/VisualDL/issues/76
  - [ ] pip 打包
  - [ ] docker
  - [x] 添加版权信息
- release
  - [ ] online demo https://github.com/PaddlePaddle/VisualDL/issues/69
  - [ ] documents https://github.com/PaddlePaddle/VisualDL/issues/83

**Comment by ShenYuhan** [comment]
visualdl2.0.0已经全面重构前端和后端架构，此TODO已失效
